.SH IPX ADDRESS FAMILY
This section documents the methods available in the
ipx address family.
.SS The static Method
This method may be used to setup an IPX interface. It requires the \fIipx_interface\fP command. 
.PP
.B Options
.RS
.TP
.BI frame " type            "
\fItype\fP of Ethernet frames to use (e.g. \fB802.2\fP)
.TP
.BI netnum " id             "
Network number
.RE
.SS The dynamic Method
This method may be used to setup an IPX interface dynamically. 
.PP
.B Options
.RS
.TP
.BI frame " type            "
\fItype\fP of Ethernet frames to use (e.g. \fB802.2\fP)
.RE
